image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -r requirements.txt
    command: |
      echo "Starting FastAPI server in development mode..."
      DEV_MODE=true uvicorn main:app --host 0.0.0.0 --port 8000 --reload

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance

ports:
  - port: 8000
    onOpen: open-preview
