image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -r requirements.txt
    command: |
      echo "Starting FastAPI server in development mode..."
      DEV_MODE=false python main.py

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance

ports:
  - port: 8000
    onOpen: open-preview
