image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -r requirements.txt
    command: |
      echo "Starting FastAPI server in development mode..."
      DEV_MODE=true python main.py

ports:
  - port: 8000
    onOpen: open-preview
