image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -r requirements.txt
    command: |
      echo "Welcome to your Python project!"
      python --version

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance

ports:
  - port: 8000
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
