steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/demos-00134568945/demos/fastapi-log-generator:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/demos-00134568945/demos/fastapi-log-generator:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'fastapi-log-generator-structlog'
    - '--image'
    - 'us-central1-docker.pkg.dev/demos-00134568945/demos/fastapi-log-generator:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'DEV_MODE=false'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'fastapi-log-generator-rich'
    - '--image'
    - 'us-central1-docker.pkg.dev/demos-00134568945/demos/fastapi-log-generator:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'DEV_MODE=false'

images:
  - 'us-central1-docker.pkg.dev/demos-00134568945/demos/fastapi-log-generator:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY